Create procedure Etut
as
Select ID,DERSAD,(TBLOGRETMEN.AD+' '+TBLOGRETMEN.SOYAD) AS 'Öðretmen' ,
(TBLOGRENCI.AD+' '+TBLOGRENCI.SOYAD) AS 'Öðrenci',TARIH,SAAT,DURUM  
FROM TBLETUT
INNER JOIN TBLDERSLER 
ON 
TBLETUT.DERSID=TBLDERSLER.DERSID 
INNER JOIN TBLOGRETMEN 
ON
TBLETUT.OGRETMENID=TBLOGRETMEN.OGRTID 
INNER JOIN TBLOGRENCI 
ON
TBLETUT.OGRENCIID=TBLOGRENCI.OGRID